ALTER TABLE "User" ADD COLUMN "trustLevel" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "User" ADD COLUMN "tensionLevel" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "energyLevel" INTEGER NOT NULL DEFAULT 50;
